version: 2

project_name: lane

builds:
  - id: lane
    main: ./main.go
    binary: lane
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/dlinardi/lane/cmd.version={{.Version}}
      - -X github.com/dlinardi/lane/cmd.commit={{.Commit}}
      - -X github.com/dlinardi/lane/cmd.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
